// src/components/layout/account/list.tsx
'use client'

import { BadgeDollarSignIcon, PenSquare, PlusCircleIcon, Trash2Icon } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'

import { formatCurrency } from '@/utils/currency'

import type { AccountWithTypeProps } from '@/types/schema'
import type { PageActions } from '@/types/pages'

import { useAppStore } from '@/store'

interface AccountListProps {
  handleAction: (
    action: PageActions,
    selected: AccountWithTypeProps
  ) => void
}

function AccountList({ handleAction }: AccountListProps) {
  const { state:{ accounts } } = useAppStore()
  
  return (
    <div className="grid grid-cols-2 grid-rows-1 gap-4 mt-6">
      {accounts.map(account => {
        return (
          <Card key={account.id}>
            <CardHeader>
              <div className="flex">
                <div className="flex-auto">
                  <CardTitle className="font-medium">
                    {account.name}
                  </CardTitle>
                  <CardDescription className="mt-0.5">
                    {account.type.description}
                  </CardDescription>
                </div>
                <div className="flex gap-2">
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => handleAction('edit', account)}
                  >
                    <PenSquare strokeWidth={1.5} color="#3B82F6" />
                  </Button>
                  <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => handleAction('remove', account)}
                  >
                    <Trash2Icon strokeWidth={1.5} color="#DC2626" />
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="flex-auto">
                <span className="text-card-foreground font-medium">
                  Saldo atual:
                  <span className="text-green-500 ml-2">
                    {formatCurrency({ value: Number(account.balance) })}
                  </span>
                </span>
              </div>
            </CardContent>
            <CardFooter>
              <div className="flex w-full">
                <div className="flex basis-1/3">
                  <Button
                    variant="ghost"
                    onClick={() => handleAction('earning', account)}
                  >
                    <PlusCircleIcon strokeWidth={1} color="#22C55E" className="mr-2" />
                    <span className="font-light">
                      Receitas
                    </span>
                  </Button>
                </div>
                <div className="flex basis-1/3">
                  <Button
                    variant="ghost"
                    onClick={() => handleAction('expense', account)}
                  >
                    <PlusCircleIcon strokeWidth={1} color="#DC2626" className="mr-2" />
                    <span className="font-light">
                      Despesas
                    </span>
                  </Button>
                </div>
                <div className="flex basis-1/3">
                  <Button
                    variant="ghost"
                    onClick={() => handleAction('transaction', account)}
                  >
                    <BadgeDollarSignIcon strokeWidth={1} color="#64748B" className="mr-2" />
                    <span className="font-light">
                      Transações
                    </span>
                  </Button>
                </div>
              </div>
            </CardFooter>
          </Card>
        )
      })}
    </div>
  )
}

export default AccountList

// components/Account/List.vue
<script setup lang="ts">
import type { Account } from "@prisma/client"
import type { ItemActionType } from "~/types"
import type { AccountWithIncludes } from "~/store/account"
import { formatCurrency } from "~/utils/currency"

const props = defineProps<{
  accounts: AccountWithIncludes[]}
>()

const emit = defineEmits<{
  (e: 'handleClick', account: Account, action: ItemActionType): void
}>()
</script>

<template>
  <div class="grid grid-cols-2 grid-rows-1 gap-4 mt-6">
    <div
      v-for="account in props.accounts"
      class="bg-white border border-black[0.07] rounded-2xl p-8"
    >
      <header class="flex">
        <div class="flex-auto">
          <span class="block font-bold">{{ account.name }}</span>
          <span class="block font-bold mt-4">
            Saldo atual:
            <span class="text-green-500">
              {{ formatCurrency({ value: account.balance }) }}
            </span>
          </span>
        </div>
        <div class="flex gap-4">
          <form-kit
            type="button"
            wrapper-class="flex"
            :ignore="false"
            @click="emit('handleClick', account, 'update')"
          >
            <icons-edit class="text-blue-500 hover:text-blue-400" />
          </form-kit>
          <form-kit
            type="button"
            wrapper-class="flex"
            :ignore="false"
            @click="$emit('handleClick', account, 'delete')"
          >
            <icons-delete class="text-rose-600 hover:text-rose-500" />
          </form-kit>
        </div>
      </header>

      <div class="flex gap-4 mt-6">
        <div class="basis-1/3">
          <form-kit
            type="button"
            wrapper-class="flex"
            input-class="flex gap-2"
            :ignore="false"
          >
            <icons-plus-circle class="text-lime-600 hover:text-lime-500" />
            Receita
          </form-kit>
        </div>
        <div class="basis-1/3">
          <form-kit
            type="button"
            wrapper-class="flex"
            input-class="flex gap-2"
            :ignore="false"
          >
            <icons-plus-circle class="text-red-600 hover:text-red-500" />
            Despesa
          </form-kit>
        </div>
        <div class="basis-1/3">
          <form-kit
            type="button"
            wrapper-class="flex"
            input-class="flex gap-2"
            :ignore="false"
          >
            <icons-transaction />
            Transações
          </form-kit>
        </div>
      </div>
    </div>
  </div>
</template>
