// pages/categories/new.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import type { CategoryType as ICategoryType } from "@prisma/client";

import FormInput from '~/components/Form/FormInput.vue';
import Select from '~/components/Form/FormSelect.vue';
import Button from '~/components/TheButton.vue';

const categoryTypes: any = ref<ICategoryType[]>([])

onMounted(async () => {
  const { data } = await useFetch<ICategoryType[]>('/api/category/type')
  categoryTypes.value = data.value
})

const handleSubmit = async (event: Event) => {
  const form = event.target as HTMLFormElement
  const formData = new FormData(form)

  await useFetch('/api/category', {
    method: 'post',
    body: {
      name: formData.get("name"),
      typeId: formData.get("typeId"),
    }
  })

  form.reset()
}
</script>

<template>
  <h2 class="text-2xl">Cadastrar nova categoria</h2>

  <div class="max-w-xl m-auto mt-8 p-6 rounded-lg shadow bg-gray-800 border-gray-700">
    <form novalidate @submit.prevent="handleSubmit">
      <fieldset>
        <FormInput name="name" label="Descrição" />
      </fieldset>

      <div class="flex mt-6 gap-4 items-end">
        <fieldset class="flex-auto">
          <Select name="typeId" label="Tipo">
            <option selected>Selecione o tipo</option>
            <option v-for="{ id, description } in categoryTypes" :key="id" :value="id">
              {{ description }}
            </option>
          </Select>
        </fieldset>

        <NuxtLink to="type/new">
          <Button type="button" color="default">
            Tipo
          </Button>
        </NuxtLink>
      </div>

      <fieldset class="mt-6 text-end">
        <Button type="submit" color="default">
          Salvar
        </Button>
      </fieldset>
    </form>
  </div>
</template>

// app/routes/category/new.tsx
import { useState } from "react";
import { Outlet, redirect, useNavigate } from "react-router";
import { Form, useLoaderData } from "@remix-run/react";
import { json } from "@remix-run/node";
import { Button, Label, Modal, Select, TextInput } from "flowbite-react";

import type { CategoryType as ICategoryType } from "@prisma/client";
import type {
  ActionArgs,
  ActionFunction,
  LoaderFunction,
} from "@remix-run/node";

import { prisma } from "~/utils/prisma.server";

export const loader: LoaderFunction = async () => {
  const categoryTypes = await prisma.categoryType.findMany();

  return json({ categoryTypes });
};

export const action: ActionFunction = async ({ request }: ActionArgs) => {
  const formData = await request.formData();

  await prisma.category.create({
    data: {
      name: String(formData.get("name")),
      typeId: String(formData.get("typeId")),
    },
  });

  return redirect("/category");
};

export default function NewCategory() {
  const navigate = useNavigate();
  const [visible] = useState(true);
  const { categoryTypes } = useLoaderData();

  const handleToogle = () => navigate("/category");

  return (
    <>
      <Outlet />

      <Modal show={visible} position="top-center" onClose={handleToogle}>
        <Form method="post">
          <Modal.Header>Cadastrar categoria</Modal.Header>
          <Modal.Body>
            <Label htmlFor="name" value="Descrição" />
            <TextInput id="name" name="name" required />

            <div className="mt-4 flex items-end">
              <div className="flex-auto mr-4">
                <Label htmlFor="typeId" value="Tipo" />
                <Select id="typeId" name="typeId" required>
                  <option value="">Selecione o tipo</option>
                  {categoryTypes.map((item: ICategoryType) => {
                    return (
                      <option key={item.id} value={item.id}>
                        {item.description}
                      </option>
                    );
                  })}
                </Select>
              </div>
              <Button onClick={() => navigate("/category/new/type")}>
                Tipo
              </Button>
            </div>
          </Modal.Body>
          <Modal.Footer className="flex justify-end">
            <Button type="submit">Salvar</Button>
          </Modal.Footer>
        </Form>
      </Modal>
    </>
  );
}
