// components/MonthYearSelected.vue
<script setup lang="ts">
import { formatDate } from "~/utils/date"
import { firstLetterUppercase } from "~/utils/string"

import type { DateSelected } from "~/types"

const optionsDefault: Intl.DateTimeFormatOptions = { month: 'long', year: 'numeric' }

const months = ref<string[]>([])
const dateSelected = ref<Date>(new Date())
const formatOptions = ref<Intl.DateTimeFormatOptions>(optionsDefault)
const shouldShowSelectDateByMonth = ref<boolean>(false)

const emit = defineEmits<{
  (e: 'handleClickDateSelect', dateSelected: DateSelected)
}>()

onMounted(() => {
  [...Array(12).keys()].map(index => {
    const month = formatDate({
      date: new Date(1990, index),
      formatOptions: { month: "short" }
    })

    months.value.push(firstLetterUppercase(month).replace('.', ''))
  })
})

const monthYearLabel = computed(() => {
  const finalDate = formatDate({
    date: dateSelected.value,
    formatOptions: formatOptions.value
  })

  return firstLetterUppercase(finalDate)
})

const toggleShowSelectByMonth = () => {
  shouldShowSelectDateByMonth.value = !shouldShowSelectDateByMonth.value
}

const setDateSelected = (date: Date = new Date(), options: Intl.DateTimeFormatOptions = optionsDefault) => {
  dateSelected.value = date
  formatOptions.value = options
}

const handleShowMonths = () => {
  if (!shouldShowSelectDateByMonth.value) {
    formatOptions.value = { year: 'numeric' }
    toggleShowSelectByMonth()
  }
}

const handleNavigateDate = (value): void => {
  if (!value) {
    setDateSelected()
    toggleShowSelectByMonth()
    return void 0
  }

  const currentDate = dateSelected.value
  let newDate: Date

  if (shouldShowSelectDateByMonth.value) {
    const newValue = value > 0 ? currentDate.getFullYear() + 1 : currentDate.getFullYear() - 1

    newDate = currentDate.setFullYear(newValue)
  } else {
    const newValue = value > 0 ? currentDate.getMonth() + 1 : currentDate.getMonth() - 1

    newDate = currentDate.setMonth(newValue)
  }

  dateSelected.value = new Date(newDate)
}

const handleSelectDate = (value) => {
  const currentDate = dateSelected.value
  const newDate = currentDate.setFullYear(currentDate.getFullYear(), value)

  setDateSelected(new Date(newDate))
  toggleShowSelectByMonth()
}

watchEffect(() => {
  if (!shouldShowSelectDateByMonth.value) {
    emit('handleClickDateSelect', {
      month: dateSelected.value.getMonth().toString(),
      year: dateSelected.value.getFullYear().toString()
    })
  }
})
</script>

<template>
  <div class="flex items-center justify-center gap-4">
    <form-kit
      type="button"
      wrapper-class="flex"
      :ignore="false"
      @click="handleNavigateDate(-1)"
    >
      <icons-angle class="text-purple-700 hover:text-purple-500" rotate="left" />
    </form-kit>

    <form-kit
      :label="monthYearLabel"
      type="button"
      :wrapper-class="shouldShowSelectDateByMonth ? 'w-32' : 'w-52'"
      input-class="w-full border border-2 border-purple-700 hover:border-purple-500 text-purple-700 font-medium py-2.5 px-5 rounded-full text-sm"
      label-class="text-purple-700 hover:text-purple-500 font-bold"
      @click="handleShowMonths"
    />

    <form-kit
      v-if="shouldShowSelectDateByMonth"
      label="Hoje"
      type="button"
      input-class="border border-2 border-purple-700 hover:border-purple-500 text-purple-700 font-medium py-2.5 px-5 rounded-full text-sm"
      label-class="text-purple-700 hover:text-purple-500 font-bold"
      @click="handleNavigateDate(null)"
    />

    <form-kit
      type="button"
      wrapper-class="flex"
      :ignore="false"
      @click="handleNavigateDate(+1)"
    >
      <icons-angle class="text-purple-700 hover:text-purple-500" rotate="right" />
    </form-kit>
  </div>

  <div v-if="shouldShowSelectDateByMonth" class="flex justify-center items-center gap-1 overflow-y-auto mt-4">
    <form-kit
      v-for="index of Object.keys(months)"
      :label="months[index]"
      type="button"
      input-class="border border-2 border-purple-700 hover:border-purple-500 text-purple-700 font-medium py-2.5 px-5 rounded-full text-sm"
      label-class="text-purple-700 hover:text-purple-500 font-bold"
      @click="handleSelectDate(index)"
    />
  </div>
</template>

// src/components/layout/transaction/month-year-selected.tsx
'use client'

import { ChevronLeftIcon, ChevronRightIcon } from 'lucide-react'

import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import { formatDate, monthsByLocale } from '@/utils/date'
import { useCallback, useState } from 'react'
import { firstLetterUppercase } from '@/utils/srting'

const DATE_FORMAT_OPTIONS = { month: 'long', year: 'numeric' } as Intl.DateTimeFormatOptions
export const BASE_BUTTON_CLASS = 'border border-2 border-purple-700 hover:border-purple-500 '+
  ' text-purple-700 text-sm text-purple-700 hover:text-purple-500 font-bold font-medium' +
  ' py-2.5 px-5 rounded-full'
 
function MonthYearSelected({ onDateSelected }: { onDateSelected: (month: string, year: string) => void }) {
  const [dateSelected, setDateSelected] = useState(new Date())
  const [dateTimeFormatOptions, setDateTimeFormatOptions] = useState<Intl.DateTimeFormatOptions>(DATE_FORMAT_OPTIONS)
  const [shouldShowSelectDateByMonth, setShouldShowSelectDateByMonth] = useState(false)
  
  const handleChangeDate = useCallback((value: number | Date) => {
    const currentDate = new Date(value)
    
    onDateSelected(
      monthsByLocale('en')[currentDate.getMonth()].toLowerCase(),
      currentDate.getFullYear().toString()
    )
  }, [onDateSelected])
  
  const handleShowMonths = useCallback(() => {
    if (!shouldShowSelectDateByMonth) {
      setDateTimeFormatOptions({ year: 'numeric' })
      setShouldShowSelectDateByMonth(prevState => !prevState)
    }
  }, [shouldShowSelectDateByMonth])
  
  const handleNavigateCurrentDate = useCallback((): void => {
    const currentDate = new Date()
    
    setDateSelected(currentDate)
    setDateTimeFormatOptions(DATE_FORMAT_OPTIONS)
    setShouldShowSelectDateByMonth(prevState => !prevState)
  }, [])
  
  const handleNavigateDate = useCallback((value: 'prev' | 'next' | null): void => {
    if (!value) {
      const currentDate = new Date()
      
      setDateSelected(currentDate)
      setDateTimeFormatOptions(DATE_FORMAT_OPTIONS)
      setShouldShowSelectDateByMonth(prevState => !prevState)
      handleChangeDate(currentDate)
      
      return void 0
    }
    
    const currentDate = dateSelected
    const newYear = value === 'next' ? currentDate.getFullYear() + 1 : currentDate.getFullYear() - 1
    const newMonth = value === 'next' ? currentDate.getMonth() + 1 : currentDate.getMonth() - 1
    const newDate = new Date(shouldShowSelectDateByMonth ? currentDate.setFullYear(newYear) : currentDate.setMonth(newMonth))
    
    setDateSelected(newDate)
    handleChangeDate(newDate)
  }, [dateSelected, handleChangeDate, shouldShowSelectDateByMonth])
  
  return (
    <>
      <div className="flex items-center justify-center gap-4">
        <Button variant="ghost" onClick={() => handleNavigateDate('prev')}>
          <ChevronLeftIcon color="#9333ea" />
        </Button>
  
        <Button
          variant="ghost"
          className={cn(BASE_BUTTON_CLASS, shouldShowSelectDateByMonth ? 'w-32' : 'w-52')}
          onClick={handleShowMonths}
        >
          {firstLetterUppercase(
            formatDate({
              date: dateSelected,
              formatOptions: dateTimeFormatOptions
            })
          )}
        </Button>
        
        {shouldShowSelectDateByMonth && (
          <Button
            variant="ghost"
            className={BASE_BUTTON_CLASS}
            onClick={handleNavigateCurrentDate}
          >
            Hoje
          </Button>
        )}
        
        <Button variant="ghost" onClick={() => handleNavigateDate('next')}>
          <ChevronRightIcon color="#9333ea" />
        </Button>
      </div>
      
      {shouldShowSelectDateByMonth && (
        <div className="flex justify-center items-center gap-1 overflow-y-auto mt-4">
          {Object.keys(monthsByLocale()).map(month => (
            <Button
              key={month}
              variant="ghost"
              className={BASE_BUTTON_CLASS}
              onClick={() => {
                const currentDate = dateSelected
                const newDate = new Date(currentDate.setFullYear(currentDate.getFullYear(), Number(month)))
                
                setDateSelected(newDate)
                setDateTimeFormatOptions(DATE_FORMAT_OPTIONS)
                setShouldShowSelectDateByMonth(prevState => !prevState)
                handleChangeDate(newDate)
              }}
            >
              {monthsByLocale()[Number(month)]}
            </Button>
          ))}
        </div>
      )}
    </>
  )
}

export default MonthYearSelected
